### ISSUE TITLE
ARView might not release camera when destroyed

### ISSUE THREAD

**Issue by lucas-koehler** [magic-script/magic-script-components-react-native#532]
I observed the typical symptoms of an unreleased camera (black camera area) when trying to use react native camera in the same app as the `ARView`. Also, when trying to fix this by destroying the ARView on screen switch (using react navigation and explicitly rendering `null` instead of the ARView on de-focus of the view containing the ARView) and then rendering the ARView again, the ARView had really bad performance, like as it would run two times and cause too much cpu load.

When I looked at Android's device logs I also found this while trying to start the camera.

```
Camera2ClientBase: setParameters: attempt to use a locked camera from a different process (old pid 0, new pid 15201)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: setParameters failed
04-07 13:28:22.792 15201 15201 E CAMERA_1::: java.lang.RuntimeException: setParameters failed
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at android.hardware.Camera.native_setParameters(Native Method)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at android.hardware.Camera.setParameters(Camera.java:2342)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at com.google.android.cameraview.Camera1.setDeviceOrientation(Camera1.java:890)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at com.google.android.cameraview.CameraView$1.onDisplayOrientationChanged(CameraView.java:142)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at com.google.android.cameraview.DisplayOrientationDetector.dispatchOnDisplayOrientationChanged(DisplayOrientationDetector.java:114)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at com.google.android.cameraview.DisplayOrientationDetector$1.onOrientationChanged(DisplayOrientationDetector.java:90)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged(OrientationEventListener.java:143)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:868)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at android.os.MessageQueue.nativePollOnce(Native Method)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at android.os.MessageQueue.next(MessageQueue.java:326)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at android.os.Looper.loop(Looper.java:170)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at android.app.ActivityThread.main(ActivityThread.java:6991)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at java.lang.reflect.Method.invoke(Native Method)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-07 13:28:22.792 15201 15201 E CAMERA_1::: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
:+1:
1
```

**Comment by lucas-koehler** [comment]
Might be related to https://github.com/magic-script/magic-script-components-react-native/issues/6

**Comment by darek607** [comment]
Thanks for detailed explanation! I'm going to investigate this issues.

**Comment by lucas-koehler** [comment]
Using the current master branch including this fix, I now could use the ARView and react-native-camera in the same app as long as I explicitly destroy the camera views when they are no longer shown :)
